apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1reimb-dep
  labels:
    app: api1reimb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api1reimb-api
  template:
    metadata:
      labels:
        app: api1reimb-api
    spec:
       containers:
        - env:
            - name: API2_URL
              value: http://api2:7072/api2
          image: jschuwan/api1reimb:latest
          name: api1reimb-api
          ports:
            - containerPort: 7071
          resources: {}
      restartPolicy: Always
            
---
apiVersion: v1
kind: Service
metadata:
  name: api1-service
spec:
  selector:
    app: api1reimb-api
  type: LoadBalancer
  ports:
    - port: 7071
      targetPort: 7071
