apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2reimb-dep
  labels:
    app: api1reimb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api2reimb-api
  template:
    metadata:
      labels:
        app: api2reimb-api
    spec:
      containers:
        - image: jschuwan/api2reimb:latest
          name: api2reimb-api
          ports:
            - containerPort: 7072
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api2-service
spec:
  selector:
    app: api2reimb-api
  type: LoadBalancer
  ports:
    - port: 7072
      targetPort: 7072
