server:
  port: 7071
  error:
    include-binding-errors: always
    include-message: always
---
spring:
  application:
    name: postgres
  datasource:
    username: blackjack
    password: "0racle!H"
    url: jdbc:postgresql://blackjack001.postgres.database.azure.com:5432/postgres
    gssEncMode: disable
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
       format-sql: true
       jdbc:
         lob:
           non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
